"""Draw the launcher icon from tools/logo.png (the preserved Yumina artwork).

Writes an adaptive icon into app/src/main/res: Yumina's navy with a warm glow
as the background, the logo as the foreground and a monochrome layer for
Android 13+ themed icons, plus square fallback PNGs, at every density. The
output is checked in, so build.py never needs Pillow; rerun this only when the
logo changes: python tools/make_icons.py
"""
from __future__ import annotations

import math
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter

ANDROID = Path(__file__).resolve().parents[1]
LOGO = ANDROID / "tools" / "logo.png"
RES = ANDROID / "app" / "src" / "main" / "res"
SCALES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
NAVY, GLOW = (0x0B, 0x0F, 0x19), (0x3A, 0x26, 0x18)
# Diameter of the circle around the artwork, as a share of the 108dp layer.
# Launcher masks may crop anything outside the central 66dp circle (0.61).
CONTENT = 0.58

ADAPTIVE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/tools/make_icons.py from the Yumina logo. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />
</adaptive-icon>
"""


def enclosing_circle(alpha):
    """Smallest circle (radius, cx, cy) around the visible artwork, in logo pixels."""
    step = 4
    small = alpha.resize((alpha.width // step, alpha.height // step), Image.BILINEAR)
    points = sorted({(x * step + step // 2, y * step + step // 2)
                     for y in range(small.height) for x in range(small.width) if small.getpixel((x, y)) > 24})

    def cross(o, a, b):
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])

    hull = []
    for sequence in (points, points[::-1]):  # Andrew's monotone chain: lower, then upper half
        half = []
        for p in sequence:
            while len(half) >= 2 and cross(half[-2], half[-1], p) <= 0:
                half.pop()
            half.append(p)
        hull += half[:-1]

    def radius(cx, cy):
        return max(math.hypot(x - cx, y - cy) for x, y in hull)

    xs, ys = [p[0] for p in hull], [p[1] for p in hull]
    _, bx, by = min((radius(x, y), x, y) for x in range(min(xs), max(xs), 8) for y in range(min(ys), max(ys), 8))
    return min((radius(x, y), x, y) for x in range(bx - 8, bx + 9) for y in range(by - 8, by + 9))


def artwork(logo, circle, size):
    """The logo, centred on its enclosing circle, in a transparent size x size layer."""
    r, cx, cy = circle
    scale = CONTENT * size / 2 / r
    art = logo.resize((round(logo.width * scale), round(logo.height * scale)), Image.LANCZOS)
    layer = Image.new("RGBA", (size, size))
    layer.alpha_composite(art, (round(size / 2 - cx * scale), round(size / 2 - cy * scale)))
    return layer


def background(size):
    """Yumina's navy (the web manifest's theme colour) with a soft warm glow."""
    layer = Image.new("RGBA", (size, size), NAVY + (255,))
    glow = Image.new("RGBA", (size, size), GLOW + (0,))
    r = 0.30 * size
    ImageDraw.Draw(glow).ellipse((size / 2 - r, size / 2 - r, size / 2 + r, size / 2 + r), fill=GLOW + (255,))
    layer.alpha_composite(glow.filter(ImageFilter.GaussianBlur(0.12 * size)))
    return layer.convert("RGB")


def monochrome(layer):
    """White artwork whose alpha launchers tint for themed icons. Strong or dark
    paint (the anchor, the star) stays solid; the pale flames stay faint."""
    _, saturation, value = layer.convert("RGB").convert("HSV").split()
    strong = saturation.point(lambda s: round(255 * min(1, max(0.3, (s / 255 - 0.30) / 0.25))))
    dark = value.point(lambda v: round(255 * min(1, max(0, (0.80 - v / 255) / 0.30))))
    alpha = ImageChops.multiply(layer.getchannel("A"), ImageChops.lighter(strong, dark))
    white = Image.new("RGBA", layer.size, (255, 255, 255, 0))
    white.putalpha(alpha)
    return white


def legacy(icon, size):
    """Square icon for tools that cannot draw adaptive icons: the 72dp view of
    the adaptive icon in a rounded square with the usual 2dp margin."""
    view = icon.crop((icon.width // 6, icon.width // 6, icon.width * 5 // 6, icon.width * 5 // 6))
    inner = round(size * 44 / 48)
    big = inner * 4
    mask = Image.new("L", (big, big))
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, big - 1, big - 1), radius=big * 0.2, fill=255)
    out = Image.new("RGBA", (size, size))
    out.paste(view.resize((inner, inner), Image.LANCZOS), ((size - inner) // 2,) * 2, mask.resize((inner, inner), Image.LANCZOS))
    return out


def main():
    logo = Image.open(LOGO).convert("RGBA")
    circle = enclosing_circle(logo.getchannel("A"))
    master = background(1080).convert("RGBA")
    master.alpha_composite(artwork(logo, circle, 1080))
    for density, scale in SCALES.items():
        folder = RES / f"mipmap-{density}"
        folder.mkdir(exist_ok=True)
        size = round(108 * scale)
        foreground = artwork(logo, circle, size)
        foreground.save(folder / "ic_launcher_foreground.png", optimize=True)
        background(size).save(folder / "ic_launcher_background.png", optimize=True)
        monochrome(foreground).save(folder / "ic_launcher_monochrome.png", optimize=True)
        legacy(master, round(48 * scale)).save(folder / "ic_launcher.png", optimize=True)
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(exist_ok=True)
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        (anydpi / name).write_text(ADAPTIVE, encoding="utf-8")
    print(f"Launcher icons written to {RES} (artwork circle r={circle[0]:.0f}px at {circle[1:]}).")


if __name__ == "__main__":
    main()
